### PR TITLE
Overhaul scroll thumb calculation

### LINKED ISSUE #1525: Scrollbar thumb moves offscreen
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20220101-133340-7edc5b5a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

The thumb gets rendered off-screen when there is a lot of output.

For example, after typing dmesg, the thumb is invisible:

https://user-images.githubusercontent.com/399535/148723616-935b2f81-bebe-49e3-9548-5e53297ced96.mp4

The video shows how I scroll it into screen, and back off-screen.

The more height I give the window, the less it goes offscreen. If I fullscreen the window, it looks like it's fully onscreen

### To Reproduce

Make wezterm window with ~300 pixels height, type `dmesg` on Linux.

(I haven't reproduced on nightly because I haven't had the time to look how to build that yet.)

### Configuration

```lua
return {
  enable_scroll_bar = true,
  colors = {
    scrollbar_thumb = "#f00",
  }
}
```

### Expected Behavior

Full height of the thumb is always on-screen.

### Logs

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by davidrios**
- Simplify scroll thumb calculations
- Correct thumb position when dragging with mouse
- Support border OS parameters
- Use usize for OS borders, to explicitly only accept positive integers
- Get correct tab height when using fancy tab bar
- Correctly draw depending on tab bar position
- Adjust minimum thumb size to be 1/2 of a cell height, so it has consistent size across platforms and screen densities

Fixes #1525

### CODE REVIEW

**Comment by wez** [comment]
This looks good; thanks for giving this some attention!

There's something a little wonky around the top pixel calculation.
Here's what I see on startup on my mac, if my mouse cursor happens to intersect with the new window placement:

image

then after mouse leaves the window:

image

you can see a gap above the scrollbar and the text content that goes away when the cursor leaves.

I'm not 100% sure but I think I also noticed the same sort of pixel jiggle when scrolling the thumb and/or entering text.

**Comment by davidrios** [comment]
Oh, that was actually one of the bugs, the thumb was always like that, because of the incorrect value returned in the get tab height function. On startup the function returns the original value because the tab bar element doesn't exist yet. Lemme fix it.

**Comment by davidrios** [comment]
Fixed. Had to save the height of the tab bar directly or else it would jiggle when resizing the window.

File: wezterm-gui/src/termwindow/mouseevent.rs [hunk 1]
```diff
@@ -252,18 +252,36 @@ impl super::TermWindow {
...
+        } else {
+            0.
+        };
+        let (top_bar_height, bottom_bar_height) = if self.config.tab_bar_at_bottom {
+            (0.0, tab_bar_height)
+        } else {
+            (tab_bar_height, 0.0)
+        };
+
+        let y_offset = top_bar_height + self.get_os_border().top.get() as f32;
```
Comment (wez) [inline wezterm-gui/src/termwindow/mouseevent.rs:266]:
```suggestion
        let border = self.get_os_border();
        let y_offset = top_bar_height + border.top.get() as f32;
```

File: wezterm-gui/src/termwindow/mouseevent.rs [hunk 2]
```diff
@@ -252,18 +252,36 @@ impl super::TermWindow {
...
         // in ScrollHit::thumb
         let row = ScrollHit::thumb_top_to_scroll_top(
             effective_thumb_top,
             &*pane,
             current_viewport,
-            &self.dimensions,
-            self.tab_bar_pixel_height().unwrap_or(0.),
-            self.config.tab_bar_at_bottom,
+            self.dimensions.pixel_height.saturating_sub(
+                y_offset as usize + self.get_os_border().bottom.get() + bottom_bar_height as usize,
```
Comment (wez) [inline wezterm-gui/src/termwindow/mouseevent.rs:282]:
```suggestion
                y_offset as usize + border.bottom.get() + bottom_bar_height as usize,
```

**Review by wez — APPROVED** [review]
Looks good!

**Comment by davidrios** [comment]
I'll need to tweak the tab bar drawing flow a bit, because it's still causing issues in X11. At one point at startup the fancy tab height returns a 0 and everything is drawn, but later it returns the real height but there's no redraw, so there things that depend on it stays at the wrong place.

**Comment by davidrios** [comment]
Sorry, I should have marked it as draft since I was checking it and saw issues. Next time I'll do that!

**Comment by davidrios** [comment]
That won't do, because that code runs before, it just returns 0. I was testing calling invalidate if the function return 0. That works, but I don't think it's very elegant. I think tweaking the tab drawing flow is the logical way to go here.

**Comment by davidrios** [comment]
Here's the log so you can get a feel for what's happening:

```
 2022-03-29T16:19:59.956Z TRACE config::config > Note: WEZTERM_CONFIG_FILE is set in the environment
 2022-03-29T16:19:59.957Z TRACE config::config > consider config: /home/david/.config/wezterm/wezterm.lua
 2022-03-29T16:19:59.957Z TRACE async_io::driver > block_on()
 2022-03-29T16:19:59.958Z TRACE async_io::driver > block_on: completed
 2022-03-29T16:19:59.958Z DEBUG config::config   > Apply enable_wayland=false to config
 2022-03-29T16:19:59.958Z TRACE polling::epoll   > add: epoll_fd=4, fd=6, ev=Event { key: 18446744073709551615, readable: false, writable: false }
 2022-03-29T16:19:59.958Z TRACE polling::epoll   > add: epoll_fd=4, fd=5, ev=Event { key: 18446744073709551615, readable: true, writable: false }
 2022-03-29T16:19:59.958Z TRACE polling::epoll   > new: epoll_fd=4, event_fd=5, timer_fd=Some(6)
 2022-03-29T16:19:59.958Z TRACE async_io::driver > main_loop: waiting on I/O
 2022-03-29T16:19:59.958Z TRACE async_io::reactor > process_timers: 0 ready wakers
 2022-03-29T16:19:59.958Z TRACE polling           > Poller::wait(_, None)
 2022-03-29T16:19:59.958Z TRACE polling::epoll    > wait: epoll_fd=4, timeout=None
 2022-03-29T16:19:59.958Z TRACE polling::epoll    > modify: epoll_fd=4, fd=6, ev=Event { key: 18446744073709551615, readable: true, writable: false }
 2022-03-29T16:19:59.982Z DEBUG config            > Reloaded configuration! generation=1
 2022-03-29T16:19:59.982Z TRACE mio::poll         > registering with poller
 2022-03-29T16:19:59.982Z TRACE mio::poll         > registering with poller
 2022-03-29T16:19:59.982Z TRACE mio::poll         > registering with poller
 2022-03-29T16:19:59.982Z DEBUG config            > Reloaded configuration! generation=1
 2022-03-29T16:19:59.983Z TRACE wezterm_gui       > Using configuration: ConfigHandle {...}
 2022-03-29T16:19:59.987Z TRACE wezterm_gui       > skip existing gui: config is different
 2022-03-29T16:19:59.987Z TRACE wezterm_gui       > NoConnectNoPublish
 2022-03-29T16:19:59.988Z TRACE window::os::x11::connection > picked depth 32 visual id:0x55, class:4, bits_per_rgb_value:8, colormap entries:256, masks: r=0xff0000,g=0xff00,b=0xff
 2022-03-29T16:19:59.995Z TRACE window::os::x11::connection > xsettings are {"Gdk/UnscaledDPI": Integer(98304), "Gdk/WindowScalingFactor": Integer(1), "Gtk/AutoMnemonics": Integer(1), "Gtk/ButtonImages": Integer(0), "Gtk/CanChangeAccels": Integer(0), "Gtk/ColorPalette": String("black:white:gray50:red:purple:blue:light blue:green:yellow:orange:lavender:brown:goldenrod4:dodger blue:pink:light green:gray10:gray30:gray75:gray90"), "Gtk/ColorScheme": String(""), "Gtk/CursorBlinkTimeout": Integer(10), "Gtk/CursorThemeName": String("Adwaita"), "Gtk/CursorThemeSize": Integer(24), "Gtk/DecorationLayout": String("menu:close"), "Gtk/DialogsUseHeader": Integer(1), "Gtk/EnableAnimations": Integer(1), "Gtk/EnablePrimaryPaste": Integer(1), "Gtk/FontName": String("Cantarell 11"), "Gtk/IMModule": String("gtk-im-context-simple"), "Gtk/IMPreeditStyle": String("callback"), "Gtk/IMStatusStyle": String("callback"), "Gtk/KeyThemeName": String("Default"), "Gtk/KeynavUseCaret": Integer(0), "Gtk/MenuBarAccel": String("F10"), "Gtk/MenuImages": Integer(0), "Gtk/Modules": String("canberra-gtk-module"), "Gtk/OverlayScrolling": Integer(1), "Gtk/RecentFilesEnabled": Integer(0), "Gtk/RecentFilesMaxAge":Integer(-1), "Gtk/SessionBusId": String("b3ed0529e3f998aad3199b406242dd87"), "Gtk/ShellShowsAppMenu": Integer(0), "Gtk/ShellShowsDesktop": Integer(0), "Gtk/ShowInputMethodMenu": Integer(0), "Gtk/ShowUnicodeMenu": Integer(0), "Gtk/TimeoutInitial": Integer(200), "Gtk/TimeoutRepeat": Integer(20), "Gtk/TitlebarDoubleClick": String("toggle-maximize"), "Gtk/TitlebarMiddleClick": String("none"), "Gtk/TitlebarRightClick": String("menu"), "Gtk/ToolbarIconSize": String("large"), "Gtk/ToolbarStyle": String("both-horiz"), "Net/CursorBlink": Integer(1), "Net/CursorBlinkTime": Integer(1200), "Net/DndDragThreshold": Integer(8), "Net/DoubleClickTime": Integer(400), "Net/EnableEventSounds": Integer(1), "Net/EnableInputFeedbackSounds": Integer(1), "Net/FallbackIconTheme": String("gnome"), "Net/IconThemeName": String("Yaru"), "Net/SoundThemeName": String("Yaru"), "Net/ThemeName": String("Yaru"), "Xft/Antialias": Integer(1), "Xft/DPI": Integer(98304), "Xft/HintStyle": String("hintfull"), "Xft/Hinting": Integer(1), "Xft/RGBA": String("none")}
 2022-03-29T16:19:59.995Z TRACE window::os::x11::connection > computed initial dpi: RefCell { value: 96.0 }
 2022-03-29T16:19:59.995Z TRACE mio::poll                   > registering with poller
 2022-03-29T16:19:59.995Z TRACE mio::poll                   > registering with poller
 2022-03-29T16:19:59.996Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-44635
 2022-03-29T16:19:59.997Z TRACE mux::domain                    > spawned: Child { stdin: None, stdout: None, stderr: None, .. }
 2022-03-29T16:19:59.998Z DEBUG wezterm_gui::frontend          > workspace is default, fixup windows
 2022-03-29T16:19:59.998Z TRACE mux                            > prune_dead_windows: not empty
 2022-03-29T16:19:59.998Z TRACE mux                            > prune_dead_windows: not empty
 2022-03-29T16:20:00.009Z TRACE wezterm_font::locator::font_config > listing by family took 7.918229ms to compute and is [...]
 2022-03-29T16:20:00.009Z TRACE wezterm_font::locator::font_config > found font-config match for Names { full_name: "DejaVu Sans Mono Book", family: "DejaVu Sans Mono", sub_family: Some("Book"), postscript_name: Some("DejaVuSansMono"), aliases: [] }
 2022-03-29T16:20:00.010Z TRACE wezterm_font::locator::font_config > found font-config match for Names { full_name: "DejaVu Sans Mono Bold", family: "DejaVu Sans Mono", sub_family: Some("Bold"), postscript_name: Some("DejaVuSansMono-Bold"), aliases: [] }
 2022-03-29T16:20:00.010Z TRACE wezterm_font::locator::font_config > listing by postscriptname took 62.218µs to compute and is [...]
 2022-03-29T16:20:00.011Z TRACE wezterm_font::locator::font_config > found font-config match for Names { full_name: "DejaVu Sans Mono Book", family: "DejaVu Sans Mono", sub_family: Some("Book"), postscript_name: Some("DejaVuSansMono"), aliases: [] }
 2022-03-29T16:20:00.011Z TRACE wezterm_font::locator::font_config > selected best font-config match Names { full_name: "DejaVu Sans Mono Book", family: "DejaVu Sans Mono", sub_family: Some("Book"), postscript_name: Some("DejaVuSansMono"), aliases: [] }
 2022-03-29T16:20:00.011Z TRACE wezterm_font::locator::font_config > listing by family took 55.163µs to compute and is []
 2022-03-29T16:20:00.011Z TRACE wezterm_font::locator::font_config > listing by postscriptname took 31.772µs to compute and is []
 2022-03-29T16:20:00.012Z TRACE wezterm_font::locator::font_config > matching by family 'JetBrains Mono' took 1.168476ms to compute and is Pattern(...)
 2022-03-29T16:20:00.012Z TRACE wezterm_font::locator::font_config > listing by family took 35.484µs to compute and is [...]
 2022-03-29T16:20:00.013Z TRACE wezterm_font::locator::font_config > found font-config match for Names { full_name: "Noto Color Emoji Regular", family: "Noto Color Emoji", sub_family: Some("Regular"), postscript_name: Some("NotoColorEmoji"), aliases: [] }
 2022-03-29T16:20:00.013Z TRACE wezterm_font::locator::font_config > listing by postscriptname took 43.519µs to compute and is [...]
 2022-03-29T16:20:00.013Z TRACE wezterm_font::locator::font_config > found font-config match for Names { full_name: "Noto Color Emoji Regular", family: "Noto Color Emoji", sub_family: Some("Regular"), postscript_name: Some("NotoColorEmoji"), aliases: [] }
 2022-03-29T16:20:00.013Z TRACE wezterm_font::locator::font_config > selected best font-config match Names { full_name: "Noto Color Emoji Regular", family: "Noto Color Emoji", sub_family: Some("Regular"), postscript_name: Some("NotoColorEmoji"), aliases: [] }
 2022-03-29T16:20:00.014Z TRACE wezterm_font::locator::font_config > listing by family took 40.242µs to compute and is []
 2022-03-29T16:20:00.014Z TRACE wezterm_font::locator::font_config > listing by postscriptname took 34.266µs to compute and is []
 2022-03-29T16:20:00.015Z TRACE wezterm_font::locator::font_config > matching by family 'Symbols Nerd Font Mono' took 1.212308ms to compute and is Pattern(...)
 2022-03-29T16:20:00.015Z TRACE wezterm_font::locator::font_config > listing by family took 75.613µs to compute and is []
 2022-03-29T16:20:00.015Z TRACE wezterm_font::locator::font_config > listing by postscriptname took 89.157µs to compute and is []
 2022-03-29T16:20:00.017Z TRACE wezterm_font::locator::font_config > matching by family 'Last Resort High-Efficiency' took 1.14941ms to compute and is Pattern(...)
 2022-03-29T16:20:00.018Z TRACE wezterm_font::shaper::harfbuzz     > compute metrics across these handles for size=11, dpi=96,
             theoretical pixel height 14.666666666666666: [...]
 2022-03-29T16:20:00.019Z TRACE wezterm_font::shaper::harfbuzz     > shaper wants 0 ParsedFont {...}
 2022-03-29T16:20:00.020Z DEBUG wezterm_font::ftwrap               > set_char_size computing 11 dpi=96 (pixel height=14.666666666666666)
 2022-03-29T16:20:00.021Z TRACE wezterm_font::shaper::harfbuzz     > idx 0 cell_height is 17.0789794921875, which is 2.412312825520834 away from theoretical
                     height (factor 0.16447587446732959). Seems good enough
 2022-03-29T16:20:00.021Z TRACE wezterm_font::shaper::harfbuzz     > metrics_for_idx=0, size=11, dpi=96 -> FontMetrics { cell_width: 9.0, cell_height: 17.0789794921875, descender: -4.0, underline_thickness: 0.6447601318359375, underline_position: -1.2537002563476563, cap_height_ratio: Some(0.5855150774420882), cap_height: Some(10.0), is_scaled: true, presentation: Text }
 2022-03-29T16:20:00.021Z TRACE wezterm_gui::termwindow            > using render_metrics RenderMetrics {
    descender: -4.0,
    descender_row: 15,
    descender_plus_two: 17,
    underline_height: 1,
    strike_row: 7,
    cell_size: 9x18,
}
 2022-03-29T16:20:00.021Z TRACE wezterm_gui::termwindow::render    > get tab bar height: 35.0
 2022-03-29T16:20:00.021Z TRACE wezterm_gui::termwindow            > Initial geometry was PtySize { rows: 24, cols: 80, pixel_width: 640, pixel_height: 384 } but dpi-adjusted geometry is PtySize { rows: 24, cols: 80, pixel_width: 720, pixel_height: 432 }; update the kernel pixel geometry for the ptys!
 2022-03-29T16:20:00.021Z TRACE wezterm_gui::termwindow            > TermWindow::new_window called with mux_window_id 0 PtySize { rows: 24, cols: 80, pixel_width: 720, pixel_height: 432 } Dimensions { pixel_width: 738, pixel_height: 485, dpi: 96 }
 2022-03-29T16:20:00.042Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=67 xsel=436
 2022-03-29T16:20:00.042Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=258 xsel=436
 2022-03-29T16:20:00.042Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=246 xsel=436
 2022-03-29T16:20:00.042Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=327 xsel=436
 2022-03-29T16:20:00.043Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=39 xsel=436
 2022-03-29T16:20:00.044Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=378 xsel=436
 2022-03-29T16:20:00.045Z TRACE window::egl                        > load_egl: Library@0x5620a0bb6630
 2022-03-29T16:20:00.068Z TRACE window::egl                        > initialized EGL version 1.5
 2022-03-29T16:20:00.068Z TRACE window::egl                        > using OpenGL
 2022-03-29T16:20:00.068Z TRACE window::egl                        > EGL extensions: EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_CHROMIUM_sync_control EGL_EXT_buffer_age EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_EXT_swap_buffers_with_damage EGL_IMG_context_priority EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_KHR_swap_buffers_with_damage EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_NOK_texture_from_pixmap EGL_WL_bind_wayland_display
 2022-03-29T16:20:00.068Z TRACE window::egl                        > Available Configuration(s):
 2022-03-29T16:20:00.068Z TRACE window::egl                        > ConfigInfo { ... lots of similar lines ...
 2022-03-29T16:20:00.079Z TRACE window::egl                        > ConfigInfo { config: 0x5620a0b83b40, alpha_size: Some(0), red_size: Some(8), green_size: Some(8), blue_size: Some(8), depth_size: Some(18), conformant: Some("OPENGL OPENGL_ES2 OPENGL_ES3 "), renderable_type: Some("OPENGL OPENGL_ES2 OPENGL_ES3 "), native_visual_id: Some(25), surface_type: Some("PIXMAP WINDOW ") }
 2022-03-29T16:20:00.080Z TRACE window::egl                        > Successfully created a surface using this configuration
 2022-03-29T16:20:00.081Z TRACE window::egl                        > ConfigInfo { config: 0x5620a0b7e200, alpha_size: Some(8), red_size: Some(8), green_size: Some(8), blue_size: Some(8), depth_size: Some(18), conformant: Some("OPENGL OPENGL_ES2 OPENGL_ES3 "), renderable_type: Some("OPENGL OPENGL_ES2 OPENGL_ES3 "), native_visual_id: Some(24), surface_type: Some("PBUFFER PIXMAP WINDOW ") }
 2022-03-29T16:20:00.089Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=255 xsel=436
 2022-03-29T16:20:00.089Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=251 xsel=436
 2022-03-29T16:20:00.089Z TRACE window::os::x11::window            > Ignoring CONFIGURE_NOTIFY because width,height,dpi are unchanged
 2022-03-29T16:20:00.089Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=308 xsel=436
 2022-03-29T16:20:00.090Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=254 xsel=436
 2022-03-29T16:20:00.090Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=326 xsel=436
 2022-03-29T16:20:00.090Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=260 xsel=436
 2022-03-29T16:20:00.090Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=308 xsel=436
 2022-03-29T16:20:00.090Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=308 xsel=436
 2022-03-29T16:20:00.090Z TRACE window::os::x11::window            > Ignoring CONFIGURE_NOTIFY because width,height,dpi are unchanged
 2022-03-29T16:20:00.090Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=308 xsel=436
 2022-03-29T16:20:00.091Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=260 xsel=436
 2022-03-29T16:20:00.091Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=308 xsel=436
 2022-03-29T16:20:00.092Z TRACE window::os::x11::window            > Calling focus_change(true)
 2022-03-29T16:20:00.092Z TRACE window                             > FocusChanged(true)
 2022-03-29T16:20:00.092Z TRACE wezterm_gui::termwindow            > Setting focus to true
 2022-03-29T16:20:00.092Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=260 xsel=436
 2022-03-29T16:20:00.092Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=308 xsel=436
 2022-03-29T16:20:00.093Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=260 xsel=436
 2022-03-29T16:20:00.093Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=308 xsel=436
 2022-03-29T16:20:00.094Z TRACE window::os::x11::window            > Calling focus_change(false)
 2022-03-29T16:20:00.094Z TRACE window                             > FocusChanged(false)
 2022-03-29T16:20:00.094Z TRACE wezterm_gui::termwindow            > Setting focus to false
 2022-03-29T16:20:00.094Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=260 xsel=436
 2022-03-29T16:20:00.094Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=308 xsel=436
 2022-03-29T16:20:00.097Z TRACE wezterm_gui::renderstate           > Compiling shader. context.capabilities.srgb=true
 2022-03-29T16:20:00.104Z INFO  wezterm_gui::termwindow            > OpenGL initialized! Mesa Intel(R) UHD Graphics 620 (WHL GT2) 4.6 (Compatibility Profile) Mesa 21.2.6 is_context_loss_possible=false wezterm version: 20220329-135836-27715bb3
 2022-03-29T16:20:00.104Z DEBUG wezterm_gui::frontend              > workspace is default, fixup windows
 2022-03-29T16:20:00.104Z TRACE window::os::x11::window            > coalesce a repaint
 2022-03-29T16:20:00.104Z TRACE window::os::x11::window            > About to paint, but we've never dispatched a Resized event, and thus never received a CONFIGURE_NOTIFY; querying WM for geometry
 2022-03-29T16:20:00.105Z TRACE window::os::x11::window            > geometry is 738x485 vs. our initial 738x485
 2022-03-29T16:20:00.105Z TRACE window                             > Resized { dimensions: Dimensions { pixel_width: 738, pixel_height: 485, dpi: 96 }, window_state: (empty), live_resizing: false }
 2022-03-29T16:20:00.105Z TRACE wezterm_gui::termwindow::resize    > resize event, live=false current cells: RowsAndCols { rows: 24, cols: 80 }, current dims: Dimensions { pixel_width: 738, pixel_height: 485, dpi: 96 }, new dims: Dimensions { pixel_width: 738, pixel_height: 485, dpi: 96 } window_state:(empty)
 2022-03-29T16:20:00.105Z TRACE wezterm_gui::termwindow::resize    > dimensions didn't change NOP!
 2022-03-29T16:20:00.105Z TRACE window                             > NeedRepaint
 2022-03-29T16:20:00.105Z TRACE wezterm_gui::termwindow::render    > get tab bar height: 35.0
 2022-03-29T16:20:00.107Z TRACE wezterm_gui::termwindow::render    > get_lines_with_hyperlinks_applied took 2.07934ms
 2022-03-29T16:20:00.108Z TRACE wezterm_gui::termwindow::render    > quad map elapsed 623.541µs
 2022-03-29T16:20:00.111Z TRACE wezterm_font::shaper::harfbuzz     > shape byte_len=80 `                                                                                `
 2022-03-29T16:20:00.112Z TRACE wezterm_font::rasterizer::freetype > Rasterizier wants ParsedFont {...}
 2022-03-29T16:20:00.113Z DEBUG wezterm_font::ftwrap               > set_char_size computing 11 dpi=96 (pixel height=14.666666666666666)
 2022-03-29T16:20:00.114Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 3.383034ms
 2022-03-29T16:20:00.115Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 35.081µs
 2022-03-29T16:20:00.116Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 30.674µs
 2022-03-29T16:20:00.116Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 17.933µs
 2022-03-29T16:20:00.116Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 17.489µs
 2022-03-29T16:20:00.117Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 17.402µs
 2022-03-29T16:20:00.117Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 17.411µs
 2022-03-29T16:20:00.117Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 17.488µs
 2022-03-29T16:20:00.118Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 20.915µs
 2022-03-29T16:20:00.118Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 89.584µs
 2022-03-29T16:20:00.119Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 56.819µs
 2022-03-29T16:20:00.119Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 62.447µs
 2022-03-29T16:20:00.120Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 72.522µs
 2022-03-29T16:20:00.120Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 33.576µs
 2022-03-29T16:20:00.121Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 27.401µs
 2022-03-29T16:20:00.121Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 24.036µs
 2022-03-29T16:20:00.121Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 46.864µs
 2022-03-29T16:20:00.122Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 21.705µs
 2022-03-29T16:20:00.122Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 21.895µs
 2022-03-29T16:20:00.123Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 23.948µs
 2022-03-29T16:20:00.123Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 17.684µs
 2022-03-29T16:20:00.123Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 17.805µs
 2022-03-29T16:20:00.123Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 17.377µs
 2022-03-29T16:20:00.124Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 17.191µs
 2022-03-29T16:20:00.124Z TRACE wezterm_gui::termwindow::render    > lines elapsed 16.134181ms
 2022-03-29T16:20:00.124Z TRACE wezterm_gui::termwindow::render    > quad drop elapsed 70.862µs
 2022-03-29T16:20:00.124Z TRACE wezterm_gui::termwindow::render    > repainting fancy tab bar
 2022-03-29T16:20:00.124Z TRACE wezterm_font::locator::font_config > listing by family took 98.601µs to compute and is []
 2022-03-29T16:20:00.125Z TRACE wezterm_font::locator::font_config > listing by postscriptname took 56.507µs to compute and is []
 2022-03-29T16:20:00.126Z TRACE wezterm_font::locator::font_config > matching by family 'Roboto' took 1.243381ms to compute and is Pattern(...)
 2022-03-29T16:20:00.126Z TRACE wezterm_font::locator::font_config > listing by family took 92.756µs to compute and is [Pattern(...), Pattern(...)]
 2022-03-29T16:20:00.127Z TRACE wezterm_font::locator::font_config > found font-config match for Names { full_name: "DejaVu Sans Mono Book", family: "DejaVu Sans Mono", sub_family: Some("Book"), postscript_name: Some("DejaVuSansMono"), aliases: [] }
 2022-03-29T16:20:00.128Z TRACE wezterm_font::locator::font_config > found font-config match for Names { full_name: "DejaVu Sans Mono Bold", family: "DejaVu Sans Mono", sub_family: Some("Bold"), postscript_name: Some("DejaVuSansMono-Bold"), aliases: [] }
 2022-03-29T16:20:00.128Z TRACE wezterm_font::locator::font_config > listing by postscriptname took 115.45µs to compute and is [Pattern(...)]
 2022-03-29T16:20:00.129Z TRACE wezterm_font::locator::font_config > found font-config match for Names { full_name: "DejaVu Sans Mono Book", family: "DejaVu Sans Mono", sub_family: Some("Book"), postscript_name: Some("DejaVuSansMono"), aliases: [] }
 2022-03-29T16:20:00.129Z TRACE wezterm_font::locator::font_config > selected best font-config match Names { full_name: "DejaVu Sans Mono Book", family: "DejaVu Sans Mono", sub_family: Some("Book"), postscript_name: Some("DejaVuSansMono"), aliases: [] }
 2022-03-29T16:20:00.129Z TRACE wezterm_font::locator::font_config > listing by family took 66.617µs to compute and is []
 2022-03-29T16:20:00.129Z TRACE wezterm_font::locator::font_config > listing by postscriptname took 41.634µs to compute and is []
 2022-03-29T16:20:00.130Z TRACE wezterm_font::locator::font_config > matching by family 'JetBrains Mono' took 1.252814ms to compute and is Pattern(...)
 2022-03-29T16:20:00.130Z TRACE wezterm_font::locator::font_config > listing by family took 62.259µs to compute and is [Pattern(...)]
 2022-03-29T16:20:00.131Z TRACE wezterm_font::locator::font_config > found font-config match for Names { full_name: "Noto Color Emoji Regular", family: "Noto Color Emoji", sub_family: Some("Regular"), postscript_name: Some("NotoColorEmoji"), aliases: [] }
 2022-03-29T16:20:00.131Z TRACE wezterm_font::locator::font_config > listing by postscriptname took 51.821µs to compute and is [Pattern(...)]
 2022-03-29T16:20:00.132Z TRACE wezterm_font::locator::font_config > found font-config match for Names { full_name: "Noto Color Emoji Regular", family: "Noto Color Emoji", sub_family: Some("Regular"), postscript_name: Some("NotoColorEmoji"), aliases: [] }
 2022-03-29T16:20:00.132Z TRACE wezterm_font::locator::font_config > selected best font-config match Names { full_name: "Noto Color Emoji Regular", family: "Noto Color Emoji", sub_family: Some("Regular"), postscript_name: Some("NotoColorEmoji"), aliases: [] }
 2022-03-29T16:20:00.132Z TRACE wezterm_font::locator::font_config > listing by family took 47.059µs to compute and is []
 2022-03-29T16:20:00.132Z TRACE wezterm_font::locator::font_config > listing by postscriptname took 29.011µs to compute and is []
 2022-03-29T16:20:00.133Z TRACE wezterm_font::locator::font_config > matching by family 'Symbols Nerd Font Mono' took 1.190956ms to compute and is Pattern(...)
 2022-03-29T16:20:00.133Z TRACE wezterm_font::locator::font_config > listing by family took 52.684µs to compute and is []
 2022-03-29T16:20:00.133Z TRACE wezterm_font::locator::font_config > listing by postscriptname took 51.741µs to compute and is []
 2022-03-29T16:20:00.135Z TRACE wezterm_font::locator::font_config > matching by family 'Last Resort High-Efficiency' took 1.173312ms to compute and is Pattern(...)
 2022-03-29T16:20:00.135Z TRACE wezterm_font::shaper::harfbuzz     > compute metrics across these handles for size=12, dpi=96,
             theoretical pixel height 16: [...]
 2022-03-29T16:20:00.136Z TRACE wezterm_font::shaper::harfbuzz     > shaper wants 0 ParsedFont { names: Names { full_name: "Roboto Bold", family: "Roboto", sub_family: Some("Bold"), postscript_name: Some("Roboto-Bold"), aliases: [] }, weight: FontWeight(700), stretch: Normal, style: Normal, handle: FontDataHandle { source: BuiltIn { name: "../../assets/fonts/Roboto-Bold.ttf" }, index: 0, variation: 0, origin: BuiltIn, coverage: None }, cap_height: Some(0.7109375), synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None }
 2022-03-29T16:20:00.136Z DEBUG wezterm_font::ftwrap               > set_char_size computing 12 dpi=96 (pixel height=16)
 2022-03-29T16:20:00.137Z TRACE wezterm_font::shaper::harfbuzz     > idx 0 cell_height is 18.75, which is 2.75 away from theoretical
                     height (factor 0.171875). Seems good enough
 2022-03-29T16:20:00.137Z TRACE wezterm_font::shaper::harfbuzz     > metrics_for_idx=0, size=12, dpi=96 -> FontMetrics { cell_width: 14.0, cell_height: 18.75, descender: -4.0, underline_thickness: 0.78125, underline_position: -1.5625, cap_height_ratio: Some(0.5866666666666667), cap_height: Some(11.0), is_scaled: true, presentation: Text }
 2022-03-29T16:20:00.137Z TRACE wezterm_gui::termwindow::render    > computed tab bar Rect(738.0x0.0 at (
    0.0,
    0.0,
))
 2022-03-29T16:20:00.137Z TRACE wezterm_gui::termwindow::render    > invalidate fancy tab bar
 2022-03-29T16:20:00.138Z TRACE wezterm_gui::termwindow::render    > Allocated 2048 quads (needed 1922)
 2022-03-29T16:20:00.138Z TRACE wezterm_gui::termwindow::render    > get tab bar height: 0.0
 2022-03-29T16:20:00.142Z TRACE wezterm_gui::termwindow::render    > get_lines_with_hyperlinks_applied took 2.97903ms
 2022-03-29T16:20:00.142Z TRACE wezterm_gui::termwindow::render    > quad map elapsed 184.121µs
 2022-03-29T16:20:00.143Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 137.767µs
 2022-03-29T16:20:00.143Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 46.969µs
 2022-03-29T16:20:00.144Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 27.365µs
 2022-03-29T16:20:00.144Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 21.823µs
 2022-03-29T16:20:00.144Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 21.171µs
 2022-03-29T16:20:00.145Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 18.273µs
 2022-03-29T16:20:00.145Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 24.179µs
 2022-03-29T16:20:00.145Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 19.71µs
 2022-03-29T16:20:00.146Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 19.664µs
 2022-03-29T16:20:00.146Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 19.884µs
 2022-03-29T16:20:00.146Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 19.542µs
 2022-03-29T16:20:00.147Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 18.817µs
 2022-03-29T16:20:00.147Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 18.539µs
 2022-03-29T16:20:00.147Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 18.569µs
 2022-03-29T16:20:00.148Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 18.188µs
 2022-03-29T16:20:00.148Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 17.723µs
 2022-03-29T16:20:00.148Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 18.505µs
 2022-03-29T16:20:00.149Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 18.613µs
 2022-03-29T16:20:00.149Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 17.966µs
 2022-03-29T16:20:00.149Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 17.766µs
 2022-03-29T16:20:00.150Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 17.907µs
 2022-03-29T16:20:00.150Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 17.841µs
 2022-03-29T16:20:00.150Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 17.49µs
 2022-03-29T16:20:00.151Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 17.674µs
 2022-03-29T16:20:00.151Z TRACE wezterm_gui::termwindow::render    > lines elapsed 8.550301ms
 2022-03-29T16:20:00.151Z TRACE wezterm_gui::termwindow::render    > quad drop elapsed 22.351µs
 2022-03-29T16:20:00.151Z TRACE wezterm_gui::termwindow::render    > repainting fancy tab bar
 2022-03-29T16:20:00.151Z TRACE wezterm_gui::termwindow::render    > computed tab bar Rect(738.0x0.0 at (
    0.0,
    0.0,
))
 2022-03-29T16:20:00.151Z DEBUG wezterm_gui::termwindow::render    > paint_impl before call_draw elapsed=46.26426ms
 2022-03-29T16:20:00.152Z DEBUG wezterm_gui::termwindow::render    > paint_impl elapsed=46.869805ms
 2022-03-29T16:20:00.152Z TRACE wezterm_gui::termwindow::render    > get tab bar height: 0.0
 2022-03-29T16:20:00.153Z TRACE wezterm_gui::termwindow::render    > invalidate fancy tab bar
 2022-03-29T16:20:00.154Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=260 xsel=436
 2022-03-29T16:20:00.154Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=308 xsel=436
 2022-03-29T16:20:00.155Z DEBUG window::os::x11::connection        > Ime: -- XIM_OPEN_REPLY
 2022-03-29T16:20:00.156Z DEBUG window::os::x11::connection        > Ime: -- XIM_QUERY_EXTENSION_REPLY
 2022-03-29T16:20:00.157Z DEBUG window::os::x11::connection        > Ime: -- XIM_ENCODING_NEGOTIATION_REPLY
 2022-03-29T16:20:00.158Z TRACE polling                            > Poller::notify()
 2022-03-29T16:20:00.158Z TRACE polling::epoll                     > notify: epoll_fd=4, event_fd=5
 2022-03-29T16:20:00.158Z TRACE polling::epoll                     > new events: epoll_fd=4, res=1
 2022-03-29T16:20:00.158Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=39 xsel=436
 2022-03-29T16:20:00.158Z TRACE polling::epoll                     > modify: epoll_fd=4, fd=5, ev=Event { key: 18446744073709551615, readable: true, writable: false }
 2022-03-29T16:20:00.159Z TRACE polling                            > Poller::notify()
 2022-03-29T16:20:00.159Z TRACE polling::epoll                     > notify: epoll_fd=4, event_fd=5
 2022-03-29T16:20:00.159Z TRACE async_io::reactor                  > process_timers: 0 ready wakers
 2022-03-29T16:20:00.159Z TRACE window                             > Notification(Any { .. })
 2022-03-29T16:20:00.159Z TRACE async_io::reactor                  > react: 0 ready wakers
 2022-03-29T16:20:00.159Z TRACE async_io::driver                   > main_loop: waiting on I/O
 2022-03-29T16:20:00.159Z TRACE async_io::reactor                  > process_timers: 0 ready wakers
 2022-03-29T16:20:00.159Z TRACE window                             > Notification(Any { .. })
 2022-03-29T16:20:00.159Z TRACE polling                            > Poller::wait(_, Some(15.540406ms))
 2022-03-29T16:20:00.159Z TRACE polling::epoll                     > wait: epoll_fd=4, timeout=Some(15.540406ms)
 2022-03-29T16:20:00.159Z TRACE polling::epoll                     > modify: epoll_fd=4, fd=6, ev=Event { key: 18446744073709551615, readable: true, writable: false }
 2022-03-29T16:20:00.159Z TRACE polling::epoll                     > new events: epoll_fd=4, res=1
 2022-03-29T16:20:00.159Z TRACE polling::epoll                     > modify: epoll_fd=4, fd=5, ev=Event { key: 18446744073709551615, readable: true, writable: false }
 2022-03-29T16:20:00.159Z TRACE async_io::reactor                  > process_timers: 0 ready wakers
 2022-03-29T16:20:00.159Z TRACE async_io::reactor                  > react: 0 ready wakers
 2022-03-29T16:20:00.160Z TRACE async_io::driver                   > main_loop: waiting on I/O
 2022-03-29T16:20:00.160Z TRACE async_io::reactor                  > process_timers: 0 ready wakers
 2022-03-29T16:20:00.160Z TRACE polling                            > Poller::wait(_, Some(14.915865ms))
 2022-03-29T16:20:00.160Z TRACE polling::epoll                     > wait: epoll_fd=4, timeout=Some(14.915865ms)
 2022-03-29T16:20:00.160Z TRACE polling::epoll                     > modify: epoll_fd=4, fd=6, ev=Event { key: 18446744073709551615, readable: true, writable: false }
 2022-03-29T16:20:00.160Z DEBUG window::os::x11::connection        > Ime: -- XIM_CREATE_IC_REPLY
 2022-03-29T16:20:00.160Z DEBUG window::os::x11::connection        > Ime: -- XIM_SET_EVENT_MASK
 2022-03-29T16:20:00.167Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=260 xsel=436
 2022-03-29T16:20:00.167Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=308 xsel=436
 2022-03-29T16:20:00.175Z TRACE polling::epoll                     > new events: epoll_fd=4, res=1
 2022-03-29T16:20:00.175Z TRACE polling::epoll                     > modify: epoll_fd=4, fd=5, ev=Event { key: 18446744073709551615, readable: true, writable: false }
 2022-03-29T16:20:00.175Z TRACE async_io::reactor                  > process_timers: 1 ready wakers
 2022-03-29T16:20:00.175Z TRACE async_io::reactor                  > react: 1 ready wakers
 2022-03-29T16:20:00.175Z TRACE async_io::driver                   > main_loop: waiting on I/O
 2022-03-29T16:20:00.176Z TRACE async_io::reactor                  > process_timers: 0 ready wakers
 2022-03-29T16:20:00.176Z TRACE polling                            > Poller::wait(_, Some(977.698979ms))
 2022-03-29T16:20:00.176Z TRACE polling::epoll                     > wait: epoll_fd=4, timeout=Some(977.698979ms)
 2022-03-29T16:20:00.176Z TRACE polling::epoll                     > modify: epoll_fd=4, fd=6, ev=Event { key: 18446744073709551615, readable: true, writable: false }
 2022-03-29T16:20:00.176Z TRACE window                             > NeedRepaint
 2022-03-29T16:20:00.176Z TRACE wezterm_gui::termwindow::render    > get tab bar height: 0.0
 2022-03-29T16:20:00.178Z TRACE wezterm_gui::termwindow::render    > get_lines_with_hyperlinks_applied took 1.982155ms
 2022-03-29T16:20:00.178Z TRACE wezterm_gui::termwindow::render    > quad map elapsed 58.571µs
 2022-03-29T16:20:00.179Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 43.154µs
 2022-03-29T16:20:00.179Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 21.443µs
 2022-03-29T16:20:00.179Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 21.332µs
 2022-03-29T16:20:00.180Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 20.381µs
 2022-03-29T16:20:00.180Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 19.755µs
 2022-03-29T16:20:00.180Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 19.915µs
 2022-03-29T16:20:00.181Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 19.766µs
 2022-03-29T16:20:00.181Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 19.337µs
 2022-03-29T16:20:00.181Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 19.379µs
 2022-03-29T16:20:00.182Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 19.626µs
 2022-03-29T16:20:00.182Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 18.958µs
 2022-03-29T16:20:00.182Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 18.762µs
 2022-03-29T16:20:00.183Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 19.589µs
 2022-03-29T16:20:00.183Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 20.088µs
 2022-03-29T16:20:00.183Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 21.435µs
 2022-03-29T16:20:00.184Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 34.49µs
 2022-03-29T16:20:00.184Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 19.143µs
 2022-03-29T16:20:00.184Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 37.436µs
 2022-03-29T16:20:00.185Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 41.973µs
 2022-03-29T16:20:00.185Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 31.792µs
 2022-03-29T16:20:00.186Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 59.894µs
 2022-03-29T16:20:00.186Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 28.49µs
 2022-03-29T16:20:00.187Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 29.912µs
 2022-03-29T16:20:00.187Z TRACE wezterm_gui::termwindow::render    > shape_resolve for cluster len 80 -> elapsed 23.201µs
 2022-03-29T16:20:00.187Z TRACE wezterm_gui::termwindow::render    > lines elapsed 9.044226ms
 2022-03-29T16:20:00.188Z TRACE wezterm_gui::termwindow::render    > quad drop elapsed 119.727µs
 2022-03-29T16:20:00.188Z TRACE wezterm_gui::termwindow::render    > repainting fancy tab bar
 2022-03-29T16:20:00.188Z TRACE wezterm_font::shaper::harfbuzz     > shape byte_len=8 `1: sleep`
 2022-03-29T16:20:00.189Z TRACE wezterm_font::rasterizer::freetype > Rasterizier wants ParsedFont { names: Names { full_name: "Roboto Bold", family: "Roboto", sub_family: Some("Bold"), postscript_name: Some("Roboto-Bold"), aliases: [] }, weight: FontWeight(700), stretch: Normal, style: Normal, handle: FontDataHandle { source: BuiltIn { name: "../../assets/fonts/Roboto-Bold.ttf" }, index: 0, variation: 0, origin: BuiltIn, coverage: None }, cap_height: Some(0.7109375), synthesize_italic: false, synthesize_bold: false, synthesize_dim: false, assume_emoji_presentation: false, pixel_sizes: [], harfbuzz_features: None, freetype_load_target: None, freetype_render_target: None, freetype_load_flags: None, scale: None }
 2022-03-29T16:20:00.189Z DEBUG wezterm_font::ftwrap               > set_char_size computing 12 dpi=96 (pixel height=16)
 2022-03-29T16:20:00.191Z TRACE wezterm_gui::termwindow::render    > computed tab bar Rect(738.0x31.0 at (
    0.0,
    0.0,
))
 2022-03-29T16:20:00.192Z DEBUG wezterm_gui::termwindow::render    > paint_impl before call_draw elapsed=15.785996ms
 2022-03-29T16:20:00.192Z DEBUG wezterm_gui::termwindow::render    > paint_impl elapsed=16.206398ms
 2022-03-29T16:20:00.192Z TRACE wezterm_gui::termwindow::render    > get tab bar height: 31.0
 2022-03-29T16:20:00.194Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=260 xsel=436
 2022-03-29T16:20:00.194Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=308 xsel=436
 2022-03-29T16:20:00.195Z TRACE polling                            > Poller::notify()
 2022-03-29T16:20:00.195Z TRACE polling::epoll                     > notify: epoll_fd=4, event_fd=5
 2022-03-29T16:20:00.195Z TRACE polling::epoll                     > new events: epoll_fd=4, res=1
 2022-03-29T16:20:00.195Z TRACE polling::epoll                     > modify: epoll_fd=4, fd=5, ev=Event { key: 18446744073709551615, readable: true, writable: false }
 2022-03-29T16:20:00.195Z TRACE async_io::reactor                  > process_timers: 0 ready wakers
 2022-03-29T16:20:00.195Z TRACE async_io::reactor                  > react: 0 ready wakers
 2022-03-29T16:20:00.195Z TRACE async_io::driver                   > main_loop: waiting on I/O
 2022-03-29T16:20:00.195Z TRACE async_io::reactor                  > process_timers: 0 ready wakers
 2022-03-29T16:20:00.195Z TRACE polling                            > Poller::wait(_, Some(15.655946ms))
 2022-03-29T16:20:00.195Z TRACE polling::epoll                     > wait: epoll_fd=4, timeout=Some(15.655946ms)
 2022-03-29T16:20:00.195Z TRACE polling::epoll                     > modify: epoll_fd=4, fd=6, ev=Event { key: 18446744073709551615, readable: true, writable: false }
 2022-03-29T16:20:00.200Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=260 xsel=436
 2022-03-29T16:20:00.201Z TRACE window::os::x11::window            > PropertyNotifyEvent atom=308 xsel=436
 2022-03-29T16:20:00.211Z TRACE polling::epoll                     > new events: epoll_fd=4, res=1
 2022-03-29T16:20:00.211Z TRACE polling::epoll                     > modify: epoll_fd=4, fd=5, ev=Event { key: 18446744073709551615, readable: true, writable: false }
 2022-03-29T16:20:00.211Z TRACE async_io::reactor                  > process_timers: 1 ready wakers
 2022-03-29T16:20:00.211Z TRACE async_io::reactor                  > react: 1 ready wakers
 2022-03-29T16:20:00.211Z TRACE async_io::driver                   > main_loop: waiting on I/O
 2022-03-29T16:20:00.211Z TRACE async_io::reactor                  > process_timers: 0 ready wakers
 2022-03-29T16:20:00.211Z TRACE polling                            > Poller::wait(_, Some(941.968453ms))
 2022-03-29T16:20:00.211Z TRACE polling::epoll                     > wait: epoll_fd=4, timeout=Some(941.968453ms)
 2022-03-29T16:20:00.211Z TRACE polling::epoll                     > modify: epoll_fd=4, fd=6, ev=Event { key: 18446744073709551615, readable: true, writable: false }
 2022-03-29T16:20:00.998Z TRACE mux                                > read_pty EOF: pane_id 0
 2022-03-29T16:20:00.999Z DEBUG mux::localpane                     > child terminated, new state is Dead
 2022-03-29T16:20:00.999Z TRACE mux::window                        > Window::prune_dead_tabs: tab_id 0 is dead
 2022-03-29T16:20:01.000Z TRACE mux                                > prune_dead_windows: window is now empty
 2022-03-29T16:20:01.000Z TRACE mux                                > tab 0 is dead
 2022-03-29T16:20:01.000Z DEBUG mux                                > remove_tab_internal tab 0
 2022-03-29T16:20:01.000Z TRACE mux                                > window 0 is dead
 2022-03-29T16:20:01.000Z DEBUG mux                                > remove_window_internal 0
 2022-03-29T16:20:01.001Z TRACE mux                                > prune_dead_windows: not empty
 2022-03-29T16:20:01.001Z TRACE mux                                > checking for dead windows after EOF on pane 0
 2022-03-29T16:20:01.001Z TRACE mux                                > prune_dead_windows: not empty
 2022-03-29T16:20:01.001Z DEBUG mux                                > removing pane 0
 2022-03-29T16:20:01.001Z DEBUG mux                                > killing pane 0
 2022-03-29T16:20:01.001Z DEBUG mux::localpane                     > killing process in pane 0, state is Dead
 2022-03-29T16:20:01.002Z TRACE mux                                > prune_dead_windows: is_empty, send MuxNotification::Empty
 2022-03-29T16:20:01.002Z TRACE wezterm_gui::frontend              > Mux is now empty, terminate gui
```

**Comment by wez** [comment]
It looks like the tab bar is sometimes 0 height? How does that happen?

**Comment by davidrios** [comment]
Yeah, exactly.

**Comment by wez** [comment]
@davidrios found it: 808d7df8d44f489680bd704d77fe23e5951cc79d
