### PR TITLE
windows: Add option to treat left ctrl-alt as altgr

### LINKED ISSUE #472: Windows: All Ctrl-Alt-key incorrectly sends Alt-key
## Describe the bug

TSIA

## Environment

 - OS: Windows (double checked, Linux is ok)
 - Version: 20210203-095643-70a364eb-26-g9bf419eb~

## Configuration

```lua
return {
  -- tested with and without
  use_dead_keys = false,
}
```

## To Reproduce

1. Open an ssh connection to a (linux) server
    _(local shells are also broken w.r.t keys, but I think it's another topic since other terminals have the same behavior)_
2. Open cat
3. Press Ctrl-Alt-z (or any alpha keys)

## Expected behavior

Observe the output `^[z` (Alt-z) instead of `^[^Z` (Alt-Ctrl-z)

### PR DESCRIPTION
**Pull request by bew**
The previous behavior was to always treat ctrl-alt as altgr on Windows,
this has been done to better support altgr through a VNC session,
but this is very unintuitive when you don't need this behavior.

Closes #472

### CODE REVIEW

File: window/src/os/windows/window.rs [hunk 1]
```diff
@@ -1579,14 +1579,20 @@ unsafe fn key(hwnd: HWND, msg: UINT, wparam: WPARAM, lparam: LPARAM) -> Option<L
             // We set RIGHT_ALT as a hint to ourselves that AltGr is in
             // use (we use regular ALT otherwise) so that our dead key
             // resolution can do the right thing.
-            //
+            modifiers |= Modifiers::RIGHT_ALT;
+        } else if config().treat_left_ctrlalt_as_altgr()
```
Comment (wez) [inline window/src/os/windows/window.rs:1583]: Should also constrain this to layouts with AltGr mappings:

```suggestion
        } else if inner.keyboard_info.has_alt_gr()
 && config().treat_left_ctrlalt_as_altgr()
```

File: docs/config/keys.md [hunk 2]
```diff
@@ -100,6 +100,24 @@ return {
 }
 ```
 
+### Microsoft Windows and Ctrl-Alt <-> AltGr
+
+*since: nightly*
+
+If you are using a layout with an *AltGr* key, you may experience issues
```
Comment (wez) [inline docs/config/keys.md:107]: Please also add a `docs/config/lua/config/treat_left_ctrlalt_as_altgr.md` with this information inside it.

It's unfortunate to duplicate the content in two places, and this particularly page is already quite long, so I'd suggest moving this block into that separate page, and then here in this doc you can have a shorter paragraph that says:

> If you are using VNC and a keyboard layout with dead keys, then you may wish to enable \[treat_left_ctrlalt_as_altgr\](lua/config/treat_left_atrlalt_as_altgr.md).

Please also add a line to `docs/changelog.md` summarizing this PR and linking to that new doc page!

**Review by wez — CHANGES_REQUESTED** [review]
Looks good! A couple of minor things to tweak before we merge it!

File: window/src/os/windows/window.rs (hunk 1 above)
Comment (bew) [reply window/src/os/windows/window.rs]: Done

File: docs/config/keys.md (hunk 2 above)
Comment (bew) [reply docs/config/keys.md]: Done!
